name: staggered_grid
description: Support staggered grid
version: 1.0.1
homepage: https://github.com/qq1023308356/staggered_grid

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

